### ISSUE TITLE
Misalignment Face

### ISSUE THREAD

**Issue by MKFMIKU** [celebv-text/CelebV-Text#1]
Almost all downloaded videos show misalignment face.  
<img width="857" alt="Screenshot 2023-01-16 at 3 18 34 PM" src="https://user-images.githubusercontent.com/13622651/212759536-2453b121-a46a-4d85-8925-3bedf60250e7.png">

**Comment by celebv-text** [comment]
Hi @MKFMIKU, the issue has been fixed.
