### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by xiangjun-xj** [celebv-text/CelebV-Text#10]
I haven't downloaded the dataset. Do all the videos contain audios of the corresponding speech? And I'd like to know whether the language is English.

**Comment by akankshasingh25** [comment]
I don't think all the videos are in English. We tried downloading a few videos from [here](https://github.com/celebv-text/CelebV-Text/blob/c256d2ad2e2da9af06783cc3cdf533c24e53ffa4/celebvtext_info.json), and there were other languages too.

**Comment by Crane-YU** [comment]
@xiangjun-xj Unfordunately, we cannot ensure all audios are English.

**Comment by xiangjun-xj** [comment]
> @xiangjun-xj Unfordunately, we cannot ensure all audios are English.

That's all right. Thanks.
In fact, I am more concentrated about whether the videos contain audios of the corresponding speech.

**Comment by zhuhaozh** [comment]
> > @xiangjun-xj Unfordunately, we cannot ensure all audios are English.
> 
> That's all right. Thanks. In fact, I am more concentrated about whether the videos contain audios of the corresponding speech.

Audio&video can be downloaded here #8
