### ISSUE TITLE
CelebV-Text vs CelebV-HQ

### ISSUE THREAD

**Issue by ziyannchen** [celebv-text/CelebV-Text#13]
Hey, there, thanks for bringing us the awesome CelebV-Text.
I'm wondering if there is any overlap between samples from CelebV-Text and [CelebV-HQ](https://github.com/CelebV-HQ/CelebV-HQ)？

**Comment by zhuhaozh** [comment]
Hi, there's no overlap between these two datasets

**Comment by zycXD** [comment]
Thanks for the reply, this is very helpful.
Another question here, we noticed there are a lot of private youtube videos in the meta json which we couldn't access.
If there is any way we could download these private videos as well?

**Comment by ziyannchen** [comment]
Thanks a lot, this is very helpful!
Regards.
