### ISSUE TITLE
can't understand annotation

### ISSUE THREAD

**Issue by akk-123** [celebv-text/CelebV-Text#14]
@zhuhaozh @celebv-text  your annotaion file is so confusing，pkl includue act and app like this 
```
[['talk', ['0:0:58', '0:1:16', 18, 0]],
  ['smile', ['0:0:58', '0:1:16', 18, 0]]],

{'scar': [''],
  'mole': [''],
  'freckle': [''],
  'dimple': [''],
  'oneeyed': [''],
  'lighting': [['frontal', ['0:0:58', '0:1:16', 18]]]}
```

how to get annotation text like paper?
![image](https://github.com/celebv-text/CelebV-Text/assets/98469560/b7e54350-527d-44d2-b115-e640509e4a0e)

**Comment by Changezi001** [comment]
The text descriptions are given in emotion and action files:

emotion: https://drive.google.com/file/d/18V-72aa36r3ZTmu2NHZIMM8aW-0PdKC-/view

action: https://drive.google.com/file/d/1N6Xf2GGstyj--taKnRi5gBd-pXAQX3cI/view

**Comment by celebv-text** [comment]
Hi @akk-123 , plz see https://github.com/celebv-text/CelebV-Text/issues/16. If you have any questions, plz let me know.
