### ISSUE TITLE
Many clips are unavailable

### ISSUE THREAD

**Issue by deeptimhe** [celebv-text/CelebV-Text#3]
Many clips are deleted from YouTube or private which cannot be directly downloaded.
e.g., 
ERROR: [youtube] qWwTuN9E198: Video unavailable
ERROR: [youtube] w9o4HhYhV2g: Private video. Sign in if you've been granted access to this video
Is there additional way to download the complete video data?

**Comment by celebv-text** [comment]
Hi @deeptimhe,
Thanks for the feedback. We are still trying to figure this out and filter out the videos that are no longer publicly available , while adding more new videos from Youtube. The current solution would be skip the videos that cannot be downloaded successfully.
