### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by sunmeng7** [celebv-text/CelebV-Text#6]
Thanks for your outstanding work!

When I download the dataset, I meet the error as follows:
`
yt-dlp  -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --skip-unavailable-fragments --merge-output-format mp4 https://www.youtube.com/watch?v=oC9r-CTbToE --output ./downloaded_celebvtext/raw/oC9r-CTbToE.mp4 --external-downloader aria2c --external-downloader-args "-x 16 -k 1M"
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
[youtube] Extracting URL: https://www.youtube.com/watch?v=oC9r-CTbToE
[youtube] oC9r-CTbToE: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address>
[youtube] oC9r-CTbToE: Downloading android player API JSON
WARNING: [youtube] <urlopen error [Errno 99] Cannot assign requested address>. Retrying (1/3)...
[youtube] oC9r-CTbToE: Downloading android player API JSON
WARNING: [youtube] <urlopen error [Errno 99] Cannot assign requested address>. Retrying (2/3)...
[youtube] oC9r-CTbToE: Downloading android player API JSON
WARNING: [youtube] <urlopen error [Errno 99] Cannot assign requested address>. Retrying (3/3)...
[youtube] oC9r-CTbToE: Downloading android player API JSON
[youtube] oC9r-CTbToE: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: <urlopen error [Errno 99] Cannot assign requested address>
[youtube] oC9r-CTbToE: Downloading web player API JSON
WARNING: [youtube] <urlopen error [Errno 99] Cannot assign requested address>. Retrying (1/3)...
[youtube] oC9r-CTbToE: Downloading web player API JSON
WARNING: [youtube] <urlopen error [Errno 99] Cannot assign requested address>. Retrying (2/3)...
[youtube] oC9r-CTbToE: Downloading web player API JSON
WARNING: [youtube] <urlopen error [Errno 99] Cannot assign requested address>. Retrying (3/3)...
[youtube] oC9r-CTbToE: Downloading web player API JSON
WARNING: [youtube] Unable to download API page: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))
ERROR: [youtube] oC9r-CTbToE: Unable to download API page: <urlopen error [Errno 99] Cannot assign requested address> (caused by URLError(OSError(99, 'Cannot assign requested address')))
video not found: oC9r-CTbToE

`

I have installed yt-dlp==2023.2.17, youtube_dl, opencv-python.

How could I solve it?

Looking forward your reply.

**Comment by Crane-YU** [comment]
hi @sunmeng7,
It seems like the issue is related to your internet connction. Do you have the vpn on?

**Comment by sunmeng7** [comment]
> hi @sunmeng7, It seems like the issue is related to your internet connction. Do you have the vpn on?
Thank you for your reply.

Sorry, my server doesn't have vpn.

Is there another way to get the dataset?

**Comment by Crane-YU** [comment]
Hi @sunmeng7,
So far we can only share the metadata for you to download the youtube videos yourself due to some privacy issue.
I'm afraid there is no way can pass around this issue.
