### ISSUE TITLE
Emotion time information

### ISSUE THREAD

**Issue by Jaeckel-d** [celebv-text/CelebV-Text#7]
Thanks for your outstanding work again!

When I was reading the paper, I found that the annotated dynamic attributes include actions and emotion. In the publicly available annotated data, there is time information about the annotation data for actions. May I ask if there is relevant time information for emotion changes and if this part of the annotation data can be made public? Looking forward to your reply.

**Comment by zhuhaozh** [comment]
I'm not sure that we provided precise information you want, but we released the metadata of the annotations, it contains the information about the emotion. 
Please check it out here: [link](https://github.com/celebv-text/CelebV-Text#1-text-descriptions--metadata-annotation)

**Comment by Changezi001** [comment]
Yes, the [annotations.pkl](https://drive.google.com/file/d/1JyopDiLcdSZ0tDw2QIvOvwLTaN6rOhEF/view) file when read using pickle is in the form of dictionary, and this dictionary has just two key values, i.e., act and app, corresponding to actions and appearances. There is no emotion information according to my understanding, or may be I am interpreting it wrongly. I think it would be great if you could explain the structure of annotations.pkl file to clarify this confusion. For instance a single entry from the action part looks like this:
Key: zYeLz4c4qYc_15_0, Value: [['talk', ['0:03:37', '0:03:43', 6, 0]], ['head_wagging', ['0:03:41', '0:03:43', 2, 1]]]

It would be beneficial to the research community if you could explain what  6 and 0 mean in the 'talk' bracket and what 2 and 1 mean in the 'head_wagging' bracket. Do they correspond to emotion labels? 

Thank you,

**Comment by Changezi001** [comment]
@Jaeckel-d do you know what 6 and 0 mean in the 'talk' bracket and what 2 and 1 mean in the 'head_wagging' bracket in an entry from the action dict of the annotations.pkl file given below? 

Key: zYeLz4c4qYc_15_0, Value: [['talk', ['0:03:37', '0:03:43', 6, 0]], ['head_wagging', ['0:03:41', '0:03:43', 2, 1]]]
